version: 0.0
os: linux

hooks:
  ApplicationStop:
    - location: AWS/demo/codepipline/stop_container.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: AWS/demo/codepipline/start_container.sh
      timeout: 300
      runas: root
